# Generated by Django 4.2 on 2024-10-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
